#!/bin/bash

#$ -M gcooper2@nd.edu   # Email address for job notification
#$ -m abe
#$ -pe smp 3          # Specify parallel environment and legal core size
#$ -q long          # Specify queue (use ‘debug’ for development)
#$ -N Results_CH4         # Specify job name             # Specify number of tasks in array

source activate py37

python dataset_loader.py
python transfer_learning.py
python Sherpa-batched_CH4100.py

